import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { MainLayout } from '@/components/layout';
import { ReactElement, useEffect } from 'react';
import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  useEffect(() => {
    console.log('mounting');
    return () => {
      console.log('unmounting');
    };
  }, []);

  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>2022-nextjs</title>

          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>1</div>
      </div>
    </div>
  );
};

Home.Layout = MainLayout;

export default Home;
