import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css"
import { useEffect, useMemo } from 'react'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>2022-nextjs</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>1</div>
    </div>
  )
}

export default Home
